title: CDAC CCEE Learning
description: Learning materials for CDAC CCEE modules.
baseurl: "/cdac-ccee"
url: "https://yadnyeshkolte.github.io"

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: dark

# Enable search
search_enabled: true

# Navigation
nav_sort: case_insensitive

# Aux links
aux_links:
  "GitHub Repository": "https://github.com/yadnyeshkolte/cdac-ccee"

# Footer
footer_content: "Copyright &copy; 2024 CDAC CCEE"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
